import javax.swing.*;
import java.awt.*;


public class BGChooser {
    private JButton defaultButton;
    private JButton blueButton;
    private JButton greenButton;

    public JPanel bgpanel;
    private JButton orangeButton;
    private JFrame root;
    private Container pane;
    private JFrame myFrame;

    public BGChooser(JFrame _root, JFrame _myFrame) {
        super();
        root = _root;
        pane = root.getContentPane();
        myFrame = _myFrame;

        defaultButton.addActionListener(e -> {
            pane.setBackground(UIManager.getColor("Panel.background"));
            pane.repaint();
            close();
        });

        blueButton.addActionListener(e -> {
            pane.setBackground(new Color(135, 206, 250));
            pane.repaint();
            close();
        });

        greenButton.addActionListener(e -> {
            pane.setBackground(new Color(152, 251, 152));
            pane.repaint();
            close();
        });

        orangeButton.addActionListener(e -> {
            pane.setBackground(new Color(255, 142, 71));
            pane.repaint();
            close();
        });
    }

    public void close() {
        myFrame.setVisible(false);
        myFrame.dispose();
        for (Component com : pane.getComponents()) {
            com.setBackground(pane.getBackground());
        }
    }


    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        bgpanel = new JPanel();
        bgpanel.setLayout(new GridBagLayout());
        defaultButton = new JButton();
        defaultButton.setText("Default");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        bgpanel.add(defaultButton, gbc);
        final JPanel spacer1 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.ipadx = 100;
        bgpanel.add(spacer1, gbc);
        final JPanel spacer2 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.VERTICAL;
        bgpanel.add(spacer2, gbc);
        blueButton = new JButton();
        blueButton.setText("Blue");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        bgpanel.add(blueButton, gbc);
        final JPanel spacer3 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 3;
        gbc.fill = GridBagConstraints.VERTICAL;
        bgpanel.add(spacer3, gbc);
        greenButton = new JButton();
        greenButton.setText("Green");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 4;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        bgpanel.add(greenButton, gbc);
        final JPanel spacer4 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.ipadx = 100;
        bgpanel.add(spacer4, gbc);
        final JPanel spacer5 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 5;
        gbc.fill = GridBagConstraints.VERTICAL;
        bgpanel.add(spacer5, gbc);
        orangeButton = new JButton();
        orangeButton.setText("Orange");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 6;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        bgpanel.add(orangeButton, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return bgpanel;
    }
}
