import javax.swing.*;
import java.awt.*;

public class HelpPopup {
    private JTextArea textArea1;
    public JPanel helppanel;

    public HelpPopup() {
        super();
        textArea1.setText(IOHandler.loadText(IOHandler.makeRelativePath("README.txt")));
        textArea1.setCaretPosition(0);


    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        helppanel = new JPanel();
        helppanel.setLayout(new BorderLayout(0, 0));
        helppanel.setMinimumSize(new Dimension(500, 500));
        helppanel.setPreferredSize(new Dimension(800, 500));
        helppanel.setRequestFocusEnabled(true);
        final JScrollPane scrollPane1 = new JScrollPane();
        scrollPane1.setVerticalScrollBarPolicy(20);
        helppanel.add(scrollPane1, BorderLayout.CENTER);
        textArea1 = new JTextArea();
        textArea1.setEditable(false);
        scrollPane1.setViewportView(textArea1);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return helppanel;
    }
}
